### ISSUE TITLE
Got TypeError: object is not a function when using with Gulp (gulp-mocha)

### ISSUE THREAD

**Issue by tdesert** [pghalliday/mocha-sonar-reporter#3]
Hey !

I receive the following error when using mocha-sonar-reporter with gulp-mocha :

```
TypeError: object is not a function
    at Runner.<anonymous> (/.../node_modules/mocha-sonar-reporter/lib/Sonar.js:55:5)
```

At line 55 :
`log = fileLogger() || log;`
The Sonar.js file fails to instantiate fileLogger() as the environment variable `process.env.npm_package_config_mocha_sonar_reporter_outputfile` is undefined. 
It then uses this `log` object which seems to be the gulp-mocha context object passed through the gulpfile.js.

To fix this problem I had to set this env variable in my gulpfile :
`process.env.npm_package_config_mocha_sonar_reporter_outputfile = 'reports/TEST-all.xml'`so the fileLogger succeeds to instantiate.

I'm not very familiar with node and packages, but at least I would suggest to ensure this environment variable is always set to a default value, and not using this 'log' object in case of failure.

Thanks anyway for this tool that helps me a lot with Sonar ;)

**Comment by svozza** [comment]
Yes, I encountered this issue today (I run my tests using Make) and wasn't aware of the dependency on NPM. Would it be possible for the three config options to be read as environmement varaiables, e.g., `MSR_TEST_DIR`, `MSR_OUTPUT_FILE`, `MSR_CLASSNAME`? I'd be more than happy to do a PR for it.

**Comment by pghalliday** [comment]
Strictly speaking, that's how it works with NPM. NPM sets environment variables and the reporter reads those. The only problem is the names are a little unweildy (generated by NPM using its own naming convention):

```
npm_package_config_mocha_sonar_reporter_classname
npm_package_config_mocha_sonar_reporter_outputfile
npm_package_config_mocha_sonar_reporter_testdir
```

However they should be perfectly usable in a Makefile

**Comment by svozza** [comment]
Yeah, I did do that initially but in the end I just ditched `Make` and rewrote everything in pure `npm`.

**Comment by svozza** [comment]
That said, it would be nice to document those env vars in the `README` because it took me a while digging around the source code and the NPM docs to figure out how to get reports when running outside of NPM.

**Comment by pghalliday** [comment]
Added a section to the readme on use outside of `npm`
