### ISSUE TITLE
Using mocha with coffeescript compiler

### ISSUE THREAD

**Issue by Skahrz** [pghalliday/mocha-sonar-reporter#5]
I m actually developping an application using mocha with coffeescript compiler and I m using the following to make my tests :

"scripts": {
    "test": "mocha --compilers coffee:coffee-script/register -r mocha-sonar-reporter test/**/*.coffee"
  },
"config": {
    "mocha-sonar-reporter": {
      "testdir": "test",
      "outputfile": "reports/TEST-all.xml"
    }
  }

I installed the dependency and put the 
sonar.javascript.jstestdriver.reportsPath=reports
inside my sonar project file.

When I launch my npm test, it's well displayed on the shell prompt, but I dont have any TEST-all.xml file generated in ./reports  (neither somewhere else in fact)

Is this a problem with the library ? Or am I totally wrong with my implementation ?

**Comment by pghalliday** [comment]
That's strange I can't see anything wrong with your config. Although I think if it were working you should not see test output in the console at all. What version of npm are you using?

**Comment by pghalliday** [comment]
Oh wait I see it :)

The reporter option for mocha is `-R`
`-r` is for additional requires.

hope that fixes it!

**Comment by Skahrz** [comment]
Oooh, I see ! I m so sorry about that :-/ It works great ! :-D . thank you for your job

**Comment by pghalliday** [comment]
no worries :)
