### ISSUE TITLE
Include File Extension In Classname

### ISSUE THREAD

**Issue by svozza** [pghalliday/mocha-sonar-reporter#6]
I'm running version `2.8` of the Sonarqube Javascript plugin and I've found that if I don't include the `.js` extension in the classname in the test report the tests do not show up in Sonarqube. For example, if I provide the `testdir` config option:

```xml
<!-- current output -->
<testsuite>
<testcase classname="testdir/testfile" name="Does not work" time="0"/>
</testsuite>

<!-- required output -->
<testsuite>
<testcase classname="testdir/testfile.js" name="Works" time="0"/>
</testsuite>
```
I presume the behaviour of this has changed at some point since unit test importing was re-enabled in version `2.2` but would it be possible to have a boolean option in the npm config to include the file extension or not?

**Comment by pghalliday** [comment]
Does this mean that the behaviour of sonar has been improved and that the original mocha xunit reporter can be used. Bear in mind that this plugin only exists to workaround issues with classnames conflicting with file names

**Comment by svozza** [comment]
No I don't think so, if I use the normal Xunit reporter the classnames are still all messed up and not consumable by Sonarqube.

**Comment by pghalliday** [comment]
ok i think that should be easy to do then

**Comment by pghalliday** [comment]
Just a note. I'm going to add an option to append a given suffix to the classname as the source may not always actually be `*.js`

**Comment by pghalliday** [comment]
I have added a `classnameSuffix` option to version 0.1.4

**Comment by svozza** [comment]
Cool, I was just going to suggest a boolean config option that either enabled or disabled the removal of the filename's suffix but this works just as well.

**Comment by svozza** [comment]
Thanks for this btw. :) I guess this can be closed now.

**Comment by pghalliday** [comment]
I wonder if that might still be needed. The files can have any extension but I understood from your initial comment that sonar required it to be `.js`. This change was easy to make but unfortunately I don't have the bandwidth to investigate how sonar actually behaves (tbh, I no longer use sonar)

**Comment by svozza** [comment]
Yeah, they do need to be .js for the Sonarqube plugin but who know that might change so the flexibility of being able to specify the extension is a good thing. One problem though, the extension is not being appended with a `.` so the output is now:


<testsuite>
<testcase classname="testdir/testfilejs" name="Works" time="0"/>
</testsuite>

**Comment by pghalliday** [comment]
you need to set it to `.js` not just `js`

**Comment by svozza** [comment]
Doh! Yes, of course.

**Comment by pghalliday** [comment]
;)

**Comment by svozza** [comment]
Hehe. It also means I'm able to remove this abomination from my NPM file:

```
sed -i 's\/\\\" name=\/\\.js\\\" name=\/g' reports\/TEST-all.xml
```

**Comment by pghalliday** [comment]
yay :)

**Comment by svozza** [comment]
This is working great so closing. Thanks again!
